const COMPRESSIONSTATE = {
    NO_FILE_SELECTED: 'NO_FILE_SELECTED',
    FILE_SELECTED: 'FILE_SELECTED',
    COMPRESSION_IN_PROGRESS: 'COMPRESSION_IN_PROGRESS',
    READY_FOR_DOWNLOAD: 'READY_FOR_DOWNLOAD'
};


export { COMPRESSIONSTATE };
